name: SonarQube Analysis

on:
  push:
    branches:
      - main  # Nombre de tu rama principal

jobs:
  sonarqube:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '11'

      - name: SonarQube Scan
        uses: sonarsource/sonarqube-scan-action@v1
        with:
          sonar-token: ${{ secrets.SONARQUBE_TOKEN }}
          project-base-dir: './'  # Directorio base de tu proyecto
