name: SonarQube Analysis

on:
  push:
    branches:
      - main  # Cambia esto según tu rama principal
  pull_request:
    branches:
      - main  # Cambia esto según tu rama principal

jobs:
  sonarQubeTrigger:
    name: SonarQube Trigger
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: 11
        distribution: 'adopt'
    - name: Build with Maven
      run: mvn clean install -B
    - name: Run Bash command
      run: |
          sudo java -version
          echo "Ingreso bash....!"
          ls -l
          sudo apt update
          #prueba install sonar
          mkdir $HOME/sonarqube
          cd $HOME/sonarqube
          wget https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-4.8.0.2856-linux.zip
          unzip sonar-scanner-cli-4.8.0.2856-linux.zip
          sudo mv sonar-scanner-4.8.0.2856-linux sonar-scanner
          sudo mv sonar-scanner /opt/
          touch sonar-scanner.sh
          echo '#/bin/bashexport' >> sonar-scanner.sh
          echo PATH='$PATH:/opt/sonar-scanner/bin' >> sonar-scanner.sh
          sudo mv sonar-scanner.sh /etc/profile.d/
          sudo chmod 777 -R /etc/profile.d/sonar-scanner.sh
          export PATH="$PATH:/opt/sonar-scanner/bin"
          sudo ln -s /opt/sonar-scanner/bin/sonar-scanner /usr/local/bin/sonar-scanner
          sonar-scanner -v
          #
          #
          #
          #instalacion que no sirvio..     
          #wget https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-4.6.2.2472-linux.zip
          #unzip sonar-scanner-cli-4.6.2.2472-linux.zip
          #export PATH=$PWD/sonar-scanner-4.6.2.2472-linux/bin:$PATH
          #sonar-scanner -v
          sonar-scanner -Dsonar.java.binaries=. -Dsonar.host.url=${{ secrets.SONAR_HOST_URL }} -Dsonar.login=${{ secrets.SONAR_TOKEN }} -Dsonar.projectName=mavenApp -Dsonar.projectKey=mavenApp -Dsonar.branch.name=main -Dsonar.coverage.jacoco.xmlReportPaths=build/customJacocoReportDir/test/jacocoTestReport.xml
          #mvn clean verify sonar:sonar -Dsonar.projectKey=testingbpop_mavenApp_AYj5emtyUXJM9CSO92GO -Dsonar.host.url=http://test-alb-1437210607.us-east-1.elb.amazonaws.com:8444 -Dsonar.login=sqp_a09cb07d412aa7c033d6f5a3959ead5d3f74e24d
